### ISSUE TITLE
Blitzwolf SHP13 Issue

### ISSUE THREAD

**Issue by alert82** [ebaauw/homebridge-deconz#101]
getting following Error Message in the Log,

[28/01/2023, 10:44:12] [deCONZ] Blitzwolf History: History Entries: error: RangeError: The value of "value" is out of range. It must be >= -32768 and <= 32767. Received 238800000
    at new NodeError (node:internal/errors:400:5)
    at checkInt (node:internal/buffer:74:11)
    at writeU_Int16LE (node:internal/buffer:724:3)
    at Buffer.writeInt16LE (node:internal/buffer:867:10)
    at ConsumptionValue.writeEntry (/usr/local/lib/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/ServiceDelegate/History.js:84:47)
    at History.entryToBuffer (/usr/local/lib/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/ServiceDelegate/History.js:602:19)
    at History._onGetEntries (/usr/local/lib/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/ServiceDelegate/History.js:687:24)
    at CharacteristicDelegate._onGet (/usr/local/lib/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/CharacteristicDelegate.js:353:26)
    at Characteristic.emit (node:events:513:28)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2463:14

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-deconz/issues/97
