### ISSUE TITLE
Error in Homebridge

### ISSUE THREAD

**Issue by mfw2010** [ebaauw/homebridge-deconz#104]
I keep getting this error in HB, don't think it causes any issues but it just colours the logs red...any ideas?

`**[03/02/2023, 09:54:54] [deCONZ] Bee: error: SyntaxError: params.computedConsumptionDelegate: missing params.computedConsumptionDelegate
    at new History (/usr/lib/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/ServiceDelegate/History.js:425:19)
    at new Light (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Light.js:88:27)
    at Gateway.addAccessory (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:612:25)
    at Gateway.analyseFullState (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:1068:20)
    at Gateway.poll (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:903:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Gateway.heartbeat (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:339:9)
**`

**Comment by ebaauw** [comment]
Could you please attach the dump file?

**Comment by mfw2010** [comment]
[homebridge-hue.json.zip](https://github.com/ebaauw/homebridge-deconz/files/10578635/homebridge-hue.json.zip)

Attached, thanks

**Comment by ebaauw** [comment]
That's a dump file by Homebridge Hue, not by Homebridge deCONZ?

**Comment by ebaauw** [comment]
Luckily it also contains the full system state from deCONZ.  The CentraLite3 200-Sgb has a ZHAPower sensor, but no ZHAConsumption.  I don't have such device myself, so that branch of code remained untested.  Above commit should fix the error.  Also note that message is wrong, it should read `SyntaxError: params.computedConsumptionDelegate: missing params.powerDelegate at new History`.

**Comment by mfw2010** [comment]
Thanks, I could not find the download dump option from Deconz settings in Homebridge UI!
How do I get this update from homebridge-lib? Will this eventually roll into a Deconz plugin update?

**Comment by ebaauw** [comment]
It it's just a patch-level update, re-installing Homebridge deCONZ will pickup the latest homebridge-lib version.  For minor and major updates, a new version of Homebridge deCONZ will bump the dependency.

**Comment by mfw2010** [comment]
Thank you

**Comment by ebaauw** [comment]
In v0.1.3.

**Comment by sirinveen** [comment]
For your info I have the same error with a plug in version 0.1.2. Fix with the new release 0.1.3.
