### ISSUE TITLE
Error Message in Homebridge Log for a Plug

### ISSUE THREAD

**Issue by sirinveen** [ebaauw/homebridge-deconz#116]
Hi,

version 0.1.4

I receive this error continually: 

[2/17/2023, 5:41:21 PM] [deCONZ] Plug Ordinateur: error: TypeError: Cannot read properties of undefined (reading 'rpath')
    at Light.<anonymous> (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/index.js:79:51)
    at Light.emit (node:events:513:28)
    at Light.emit (/usr/lib/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/Delegate.js:173:13)
    at Gateway.analyseFullState (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:1050:34)
    at Gateway.poll (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:903:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Gateway.heartbeat (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:339:9)

Can you resolve it or do you need more info?

**Comment by ebaauw** [comment]
Does the error still occur after un-exposing and re-exposing the plug?

If so, please attach the dump file and capture a debug log file, setting `logLevel` for the plug to 2.

**Comment by sirinveen** [comment]
Hi,

un-exposing and re-exposing plug-in fix this issue. You can close the ticket. Thanks
