### ISSUE TITLE
Danfoss Ally thermostat: Cannot set properties of undefined (setting 'heatValue')

### ISSUE THREAD

**Issue by BEskandari** [ebaauw/homebridge-deconz#12]
Hello Erik,
I have 2 Danfoss Ally thermostat, working with DECONZ & Homebridge Hue. Now I get the below message in Homebridge Deconz:

[13/02/2022, 20:23:08] [deCONZ] HB-deCONZ: error: TypeError: Cannot set properties of undefined (setting 'heatValue')
    at Resource.patchThermostat (/usr/local/lib/node_modules/homebridge-deconz/lib/Deconz/Resource.js:1192:34)
    at new Resource (/usr/local/lib/node_modules/homebridge-deconz/lib/Deconz/Resource.js:248:14)
    at Gateway.analyseResource (/usr/local/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:904:22)
    at Gateway.analyseFullState (/usr/local/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:754:16)
    at Gateway.poll (/usr/local/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:669:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Gateway.heartbeat (/usr/local/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:256:9)

And they don't show up in Homekit

**Comment by ebaauw** [comment]
That's a bug alright, see https://github.com/ebaauw/homebridge-deconz/issues/6

**Comment by ebaauw** [comment]
Should be fixed in v0.0.13.
