### ISSUE TITLE
Aqara Single Switch module is not working

### ISSUE THREAD

**Issue by Daniel-56** [ebaauw/homebridge-deconz#120]
Homebridge Log:

[2/23/2023, 2:59:51â¯PM] [deCONZ] Phoscon-GW Button: Programmable Switch Event: Single Press
[2/23/2023, 2:59:52â¯PM] [deCONZ] Lumi Sofa: LUMI lumi.switch.n0agl1 v0xFFFFFFFF (5 resources)
[2/23/2023, 2:59:52â¯PM] [deCONZ] Lumi Sofa: Configured Name: warning: 1433 listeners
[2/23/2023, 2:59:52â¯PM] [deCONZ] Lumi Sofa: On: warning: 1433 listeners
[2/23/2023, 2:59:52â¯PM] [deCONZ] Phoscon-GW: error: SyntaxError: totalConsumption: duplicate key
    at Outlet.addCharacteristicDelegate (/homebridge/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/ServiceDelegate/index.js:242:13)
    at Function.addResource (/homebridge/node_modules/homebridge-deconz/lib/DeconzService/Consumption.js:18:13)
    at Outlet.addResource (/homebridge/node_modules/homebridge-deconz/lib/DeconzService/index.js:77:41)
    at Light.createService (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/index.js:149:17)
    at new Light (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Light.js:44:14)
    at Gateway.addAccessory (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:601:25)
    at Gateway.analyseFullState (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:1031:20)
    at Gateway.poll (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:868:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Gateway.heartbeat (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:333:9)

**Comment by ebaauw** [comment]
Please attach the debug dump file.

**Comment by Daniel-56** [comment]
[homebridge-deconz.json.gz](https://github.com/ebaauw/homebridge-deconz/files/10818224/homebridge-deconz.json.gz)

**Comment by Daniel-56** [comment]
i hope it helps...

**Comment by ebaauw** [comment]
The switch is exposed wrongly by deCONZ, using multiple ZHAConsumption and ZHAPower `/sensors` resources.

This needs to be solved in deCONZ.  I cannot help there; I don't own this device.  And I don't understand this device; the screenshots in  https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4328 and https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6356 are different.

> [2/23/2023, 2:59:52PM] [deCONZ] Lumi Sofa: LUMI lumi.switch.n0agl1 v0xFFFFFFFF (5 resources)

So that's the following resources:
- `/lights/7`, an _On/Off Light_ on endpoint 0x01.  I assume this is a single-button switch, controlling a single output wire?  Oddly, there's no _On/Off_ cluster on endpoint 0x01, according to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6356, but it is there on https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4328.
- `/sensors/8` a `ZHAConsumption` sensor for the 0x0702 cluster on endpoint 0x01.  According to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6356, the decice doesn't carry this cluster;
- `/sensors/9, a `ZHAPower` sensor for the 0x0B04 cluster on endpoint 0x01.  According to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6356, the device doesn't carry this cluster.
- `/sensors/10`, another `ZHAPower` sensor for the 0x000C cluster on endpoint 0x15.  I would expect Xiaomi to use _Analog Input_ for power, but 0x15 seems a high value for the endpoint;
- `/sensors/11`, another `ZHAConsumption` sensor for the 0x000C cluster on endpoint 0x1F.  I would expect Xiaomi to use _Analog Input_ for consumption, but 0x1F seems a high value for the endpoint.

**Comment by ebaauw** [comment]
Maybe a faulty DDF?
