### ISSUE TITLE
otau CLI tool doesn't work yet

### ISSUE THREAD

**Issue by JanMisker** [ebaauw/homebridge-deconz#151]
If I run `otau` on command line I get this error output:

```
$ otau
otau: fatal: SyntaxError: timeout: invalid key
    at newSyntaxError (/usr/lib/node_modules/homebridge-deconz/node_modules/hb-lib-tools/lib/OptionParser.js:28:52)
    at OptionParser.parse (/usr/lib/node_modules/homebridge-deconz/node_modules/hb-lib-tools/lib/OptionParser.js:869:17)
    at new JsonFormatter (/usr/lib/node_modules/homebridge-deconz/node_modules/hb-lib-tools/lib/JsonFormatter.js:70:18)
    at OtauTool.main (/usr/lib/node_modules/homebridge-deconz/node_modules/hb-deconz-tools/lib/OtauTool.js:74:28)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-deconz/cli/otau.js:13:23)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

**Comment by ebaauw** [comment]
My bad.  Last minute addition of `--timeout` had some unexpected side effetcs.

**Comment by JanMisker** [comment]
happens ;)

looking forward to using the tool, seems useful

**Comment by ebaauw** [comment]
I still want to add some filters, so you can download files for a single manufacturer or manufacturer/image type.  And do an info or check command to show the header info of downloaded files.

If you re-install Homebridge deCONZ, it should pickup hb-lib-tools@1.0.5, which includes the fix for `otau`.

**Comment by JanMisker** [comment]
yes, works
