### ISSUE TITLE
totalConsumption: duplicate key

### ISSUE THREAD

**Issue by torandreroland** [ebaauw/homebridge-deconz#174]
With v1.0.3 I get totalConsumption: duplicate key-SyntaxError. The error is not present after reverting to v1.0.1.

[10/6/2023, 12:53:59 PM] [deCONZ] Ekraveien 18: error: SyntaxError: totalConsumption: duplicate key
    at Power.addCharacteristicDelegate (/homebridge/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/ServiceDelegate/index.js:229:13)
    at new Light (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Light.js:92:57)
    at Gateway.addAccessory (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:625:25)
    at Gateway.analyseFullState (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:1122:20)
    at Gateway.poll (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:966:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Gateway.heartbeat (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:358:9)

homebridge-deconz.json can be [viewed here](https://1drv.ms/u/s!Am3DKtLr0F3Kg8lbhMwByGd_3BcAZw?e=urfRjP).

I have two outlets of same type named Kitchen Appliance and Kitchen Charger. This only happens with Kitchen Charger. I suspect it's something with the ordering of the resources in the deconz API.

**Comment by ebaauw** [comment]
I cannot see the json file: it requires me to login.

I just came across this yesterday, for my ubisys D1.  It happens when the ZHAPower resource comes before (has a lower resource ID than) the ZHAConsumption.
