### ISSUE TITLE
Cannot read properties of undefined (reading 'sat')

### ISSUE THREAD

**Issue by b2un0** [ebaauw/homebridge-deconz#19]
Device `LIDL Livarno Lux HG06467 Christmas Stripe`

`homebridge-deconz v0.0.13`

```plain
[2/18/2022, 4:32:34 PM] [deCONZ] Eingang Treppe: error: TypeError: Cannot read properties of undefined (reading 'sat')
    at CharacteristicDelegate.<anonymous> (/homebridge/node_modules/homebridge-deconz/lib/DeconzService/Light.js:154:42)
    at CharacteristicDelegate.emit (node:events:520:28)
    at CharacteristicDelegate.emit (/homebridge/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/Delegate.js:174:13)
    at CharacteristicDelegate._onSet (/homebridge/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/CharacteristicDelegate.js:441:10)
    at Saturation.emit (node:events:520:28)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1725:16
    at new Promise (<anonymous>)
    at Saturation.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1723:14)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
```

**Comment by ebaauw** [comment]
That's a bug alright.

Also note that I haven't yet added support for setting speed and colours for the special effects.

**Comment by ebaauw** [comment]
In v0.0.14
