### ISSUE TITLE
LightGroup with {"exposeScenes": false} cause  - error: TypeError: Cannot read properties of undefined (reading '1')

### ISSUE THREAD

**Issue by ostauss** [ebaauw/homebridge-deconz#194]
Accessory: 

 ui get /accessories/00212EFFFF05B41A-G1
```
{
  "id": "00212EFFFF05B41A-G1",
  "manufacturer": "dresden elektronik",
  "model": "LightGroup",
  "name": "XXXXX",
  "resources": [
    "/groups/1"
  ],
  "settings": {
    "expose": true,
    "exposeScenes": false,
    "logLevel": 2,
    "serviceName": "Light"
  },
  "type": "groups",
  "zigbee": false
}

```
Cause Problem (homebridge log): 

```
[4.12.2023, 10:49:32] [deCONZ] XXXXX: error: TypeError: Cannot read properties of undefined (reading '1')
    at Light.updateScenes (/var/lib/homebridge/node_modules/homebridge-deconz/lib/DeconzService/Light.js:487:29)
    at Light.update (/var/lib/homebridge/node_modules/homebridge-deconz/lib/DeconzService/index.js:115:14)
    at Light.<anonymous> (/var/lib/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/index.js:84:21)
    at Light.emit (node:events:517:28)
    at Light.emit (/var/lib/homebridge/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/Delegate.js:173:13)
    at Gateway.analyseFullState (/var/lib/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:1105:34)
    at Gateway.poll (/var/lib/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:965:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Gateway.heartbeat (/var/lib/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:357:9)

```

Thoughts on Problem: 
* Don't handle Scenes, when "exposeScenes" is false...

regards Oliver

**Comment by ebaauw** [comment]
In v1.0.8.

**Comment by ostauss** [comment]
fixed
