### ISSUE TITLE
getting error:  warning: /lights/1: Outlet: service type not available

### ISSUE THREAD

**Issue by pponce** [ebaauw/homebridge-deconz#235]
Running latest homebridge-deconz as of 12/28/24.

With latest hommebridge as of 12/28/24.

In my homebridge logs I see these errors.
No functionality seems to be lost or issues observed in daily use. The inline power switch (which appears as a "light" in deconz/phoscon) works as expected.  But I do see these errors in red in my homebridge logs.
[28/12/2024, 14:40:31] [deCONZ] Phoscon-GW: warning: Primary Bathroom Fan Socket: exposed by legacy code
[28/12/2024, 14:40:31] [deCONZ] Phoscon-GW: Primary Bathroom Fan Socket: add accessory
[28/12/2024, 14:40:32] [deCONZ] Primary Bathroom Fan Socket: SZ Lamp_01 v20181107 (1 resources)
[28/12/2024, 14:40:32] [deCONZ] Primary Bathroom Fan Socket: warning: /lights/1: Outlet: service type not available
[28/12/2024, 14:40:32] [deCONZ] Phoscon-GW: error: TypeError: Cannot read properties of undefined (reading 'length')
    at new Light (file:///var/lib/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Light.js:55:59)
    at Gateway.addAccessory (file:///var/lib/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:677:25)
    at Gateway.analyseFullState (file:///var/lib/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:1240:15)
    at Gateway.poll (file:///var/lib/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:1019:7)
    at Gateway.heartbeat (file:///var/lib/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:365:9)
    
When I run get/accessories command: 
pi@homebridge:/var/lib/homebridge/node_modules/homebridge-deconz/cli $ ./ui.js get /accessories/01124B001BAE9EB9
{
  "id": "01124B001BAE9EB9",
  "manufacturer": "SZ",
  "model": "Lamp_01",
  "name": "Primary Bathroom Fan Socket",
  "resources": [
    "/lights/1"
  ],
  "settings": {
    "expose": true,
    "logLevel": 2,
    "serviceName": "Outlet",
    "wallSwitch": false
  },
  "type": "lights",
  "zigbee": true
}

What is odd is that I have another one of these zigbee devices and I don't get the error for it.

pi@homebridge:/var/lib/homebridge/node_modules/homebridge-deconz/cli $ ./ui.js get /accessories/01124B001BAE7A4B
{
  "id": "01124B001BAE7A4B",
  "manufacturer": "SZ",
  "model": "Lamp_01",
  "name": "Upstairs Bathroom Fan Socket",
  "resources": [
    "/lights/2"
  ],
  "settings": {
    "expose": true,
    "logLevel": 2,
    "serviceName": "Outlet",
    "wallSwitch": false
  },
  "type": "lights",
  "zigbee": true
}

Any ideas what might be happening?

**Comment by ebaauw** [comment]
This looks like the error I thought I’d fixed in [v1.0.18](https://github.com/ebaauw/homebridge-deconz/releases/tag/v1.0.18).  Not sure whether a later change broke the fix or whether the fix didn’t address all situations.

Could you please **attach** the debug dump file?  I need to see if I can reproduce this issue.

**Comment by pponce** [comment]
Sure thing.
Here you go.
[homebridge-deconz.json.gz](https://github.com/user-attachments/files/18283287/homebridge-deconz.json.gz)

**Comment by ebaauw** [comment]
I think your eWeLink and Trådfri plugs cause the _Outlet_ service type to be loaded (they have `type` _On/Off plugin unit_ instead of _On/Off light_), probably between exposing the first and seconds SZ switches.  The first switch probably gets exposed correctly on the next heartbeat, after the service type has been loaded, hence no loss of functionality.

Somehow the `serviceName` setting isn't persisted as I intended, and the logic restoring the accessories from cache doesn't take it into account.  I think I have an old _On/Off light_ lying around somewhere to setup a proper test environment.

**Comment by ebaauw** [comment]
The problem seems to be that existing settings (made in Homebridge deCONZ before v1.0.18) aren't visible to the restore logic.

**Comment by pponce** [comment]
Looks to be fixed!
Worked exactly as you thought it would.
On first restart after install I saw the error.
On subsequent restart it went away.
Thanks for this plugin and homebridge hue!

**Comment by ebaauw** [comment]
In v1.0.24.
