### ISSUE TITLE
error: TypeError: Cannot read properties of undefined (reading 'mode')

### ISSUE THREAD

**Issue by Monofin** [ebaauw/homebridge-deconz#26]
Hi there, suffering from this error every few seconds or so when connecting to a deCONZ 0.14.1 gateway with a significant number of devices attached.
Previously using Homebridge Hue with no issues, I set up the auto discovery (gateway was found correctly) and enabled connection to the bridge in the phoscon web app.

(Looks like there's something in the Tradfri Dimmers that are proving an issue here - removing them from the phoscon app allowed the initialisation to proceed.)

It connected, but am stuck here:

[07/03/2022, 16:50:03] [deCONZ] flush cachedAccessories
[07/03/2022, 16:50:03] [deCONZ] Mordin: request 3: GET /config
[07/03/2022, 16:50:03] [deCONZ] Mordin: request 3: 200 OK
[07/03/2022, 16:50:03] [deCONZ] Mordin: request 4: GET /lights
[07/03/2022, 16:50:03] [deCONZ] Mordin: request 4: 200 OK
[07/03/2022, 16:50:03] [deCONZ] Mordin: request 5: GET /sensors
[07/03/2022, 16:50:03] [deCONZ] Mordin: request 5: 200 OK
[07/03/2022, 16:50:03] [deCONZ] Mordin: request 6: GET /groups
[07/03/2022, 16:50:03] [deCONZ] Mordin: request 6: 200 OK
[07/03/2022, 16:50:03] [deCONZ] Mordin: request 7: GET /groups/0
[07/03/2022, 16:50:03] [deCONZ] Mordin: request 7: 200 OK
[07/03/2022, 16:50:03] [deCONZ] Mordin: error: TypeError: Cannot read properties of undefined (reading 'mode')
    at Resource.patchSwitch (/usr/lib/node_modules/homebridge-deconz/lib/Deconz/Resource.js:659:26)
    at new Resource (/usr/lib/node_modules/homebridge-deconz/lib/Deconz/Resource.js:248:14)
    at Gateway.analyseResource (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:905:22)
    at Gateway.analyseFullState (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:754:16)
    at Gateway.poll (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:669:18)
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Gateway.heartbeat (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:256:9)

[07/03/2022, 16:50:03] [deCONZ] Mordin: error: TypeError: Cannot read properties of undefined (reading 'mode')
    at Resource.patchSwitch (/usr/lib/node_modules/homebridge-deconz/lib/Deconz/Resource.js:659:26)
    at new Resource (/usr/lib/node_modules/homebridge-deconz/lib/Deconz/Resource.js:248:14)
    at Gateway.analyseResource (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:905:22)
    at Gateway.analyseFullState (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:754:16)
    at Gateway.poll (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:669:18)
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Gateway.heartbeat (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:256:9)

[07/03/2022, 16:50:03] [deCONZ] Mordin Gateway Settings: set Last Updated from "Mon Mar 07 2022 16:49:33" to "Mon Mar 07 2022 16:50:03"

**Comment by ebaauw** [comment]
That's a bug alright, copy/pasting code from Homebridge Hue.

**Comment by Monofin** [comment]
Bugfix tested as working on original config with deCONZ gateway 0.14.1 with Tradfri dimmer, thanks!

**Comment by ebaauw** [comment]
In v0.0.14.
