### ISSUE TITLE
Adaptive lighting: 'Characteristic Value Transition Control': characteristic was supplied illegal value: undefined

### ISSUE THREAD

**Issue by Monofin** [ebaauw/homebridge-deconz#27]
With homebridge deconz and deCONZ 2.14.01, when adaptive lighting is enabled, I pick up a bunch of errors from a set of lights that all follow the same pattern.
Homebridge Deconz is running as a child bridge.

Bulbs are different manufacturers (Tuya and Ikea at least two of them) - might possibly relate to 'special effects' options on them?

[07/03/2022, 18:23:50] [homebridge-deconz] This plugin generated a warning from the characteristic 'Characteristic Value Transition Control': characteristic was supplied illegal value: undefined. See https://git.io/JtMGR for more info.
[07/03/2022, 18:23:50] [homebridge-deconz] Muservatory Drums Light: Adaptive Lighting: disabled
[07/03/2022, 18:23:50] [homebridge-deconz] Muservatory Drums Light: error: TypeError: Cannot read properties of undefined (reading 'generateControl')
    at CharacteristicDelegate.getter [as _getter] (/usr/lib/node_modules/homebridge-deconz/lib/DeconzService/Light.js:209:40)
    at CharacteristicDelegate._onGet (/usr/lib/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/CharacteristicDelegate.js:354:26)
    at CharacteristicValueTransitionControl.emit (node:events:520:28)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1592:14
    at new Promise (<anonymous>)
    at CharacteristicValueTransitionControl.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1590:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)

**Comment by ebaauw** [comment]
What version of Homebridge deCONZ are you on?  I think I saw something similar in v0.0.11, but that should have been fixed in v0.0.12.  Could you double-check if the problem still occurs in v0.0.14?  Also for a light that was un-exposed and re-exposed after updating to the latest Homebridge deCONZ version.  There might be some residual junk from an old version in `cachedAccessories`, even though there shouldn't be.
