### ISSUE TITLE
 TypeError: this.updateConfig is not a function

### ISSUE THREAD

**Issue by b2un0** [ebaauw/homebridge-deconz#40]
```
4/22/2022, 8:48:09 PM] [deCONZ] Studio Pacman: error: TypeError: this.updateConfig is not a function
    at Outlet.update (/homebridge/node_modules/homebridge-deconz/lib/DeconzService/index.js:86:12)
    at Light.<anonymous> (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/index.js:81:21)
    at Light.emit (node:events:526:28)
    at Light.emit (/homebridge/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/Delegate.js:174:13)
    at Gateway.analyseFullState (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:859:34)
    at Gateway.poll (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:712:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Gateway.heartbeat (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:258:9)
```

innr SP 120

**Comment by ebaauw** [comment]
What version of deCONZ are you running?  Could you please attach the debug dump file?

**Comment by b2un0** [comment]
Hey, sorry for my late answer.

currently it looks like the problem is gone..

![image](https://user-images.githubusercontent.com/2155498/165243428-5c654ad8-01a3-4150-b981-74a7e94c5bdd.png)


[homebridge-deconz.json.gz](https://github.com/ebaauw/homebridge-deconz/files/8560734/homebridge-deconz.json.gz)
