### ISSUE TITLE
Error with Window Covering device, but it does work

### ISSUE THREAD

**Issue by keness521** [ebaauw/homebridge-deconz#5]
Switched one of my "homes" over to homebridge-deCONZ today and it went smooth as silk!

This is a very simple home, which is why I started with it.

Devices:
 - 1 x Aqara wall switch (single rocker, with neutral, US style) - LUMI, Transmitter 1-gang, 09-06-2019
 - 1 x Aqara wall switch (double rocker, with neutral, US style) - LUMI, lumi.switch.b2naus01, 0x00000019
 - 3 x YookSmart roller shades - yooksmart, D10110, 20201120

There are errors for the roller shade devices which show up in the log. Pasted below. The device DOES work, though. The same device in homebridge-Hue did not generate any errors.

(These roller shade devices have been problematic in general. It is possible to make them work, though the open/closed/percentage reporting doesn't seem to be very reliable. One of the three behaves differently than the other two despite showing the same version. I assume this is all down to deCONZ.)

-----

[04/02/2022, 21:31:27] [deCONZ] Office Shade 1: error: TypeError: service.update is not a function
    at WindowCovering.<anonymous> (/usr/local/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/index.js:81:21)
    at WindowCovering.emit (node:events:390:28)
    at WindowCovering.emit (/usr/local/lib/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/Delegate.js:174:13)
    at Gateway.analyseFullState (/usr/local/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:812:34)
    at Gateway.poll (/usr/local/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:670:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Gateway.heartbeat (/usr/local/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:264:9)

**Comment by ebaauw** [comment]
Is this a battery-powered window covering device, with a separate ZHABattery `/sensors` resource?

**Comment by keness521** [comment]
It is. Is that what is causing the error, battery service not supported yet?

**Comment by ebaauw** [comment]
That's a very friendly way to put it.  The `update()` message is missing from the battery service delegate.  This causes the battery state not to be updated in HomeKit, but, indeed, it shouldn't impact the window covering functionality.

**Comment by ebaauw** [comment]
In v0.0.12
