### ISSUE TITLE
Elko Super not working

### ISSUE THREAD

**Issue by torandreroland** [ebaauw/homebridge-deconz#6]
I got the following error when using the plugin in a setup with Elko Super Thermostat:

[deCONZ] Ekraveien 18: error: TypeError: Cannot set properties of undefined (setting 'heatValue')
    at Resource.patchThermostat (/homebridge/node_modules/homebridge-deconz/lib/Deconz/Resource.js:1190:34)
    at new Resource (/homebridge/node_modules/homebridge-deconz/lib/Deconz/Resource.js:248:14)
    at Gateway.analyseResource (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:904:22)
    at Gateway.analyseFullState (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:754:16)
    at Gateway.poll (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:669:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Gateway.heartbeat (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:256:9)

**Comment by ebaauw** [comment]
Indeed, thanks!

**Comment by ebaauw** [comment]
In v0.0.13.
