### ISSUE TITLE
Friends of Hue button errors in 0.0.18 build

### ISSUE THREAD

**Issue by ctj99git** [ebaauw/homebridge-deconz#62]
I just installed the 0.0.18 build and got these errors in the console:

`[8/8/2022, 9:51:56 AM] [deCONZ] FoH Master Bedroom: error: TypeError: Cannot read properties of undefined (reading 'lastUpdated')
    at Switch.updateState (/usr/lib/node_modules/homebridge-deconz/lib/DeconzService/Switch.js:62:24)
    at Switch.update (/usr/lib/node_modules/homebridge-deconz/lib/DeconzService/index.js:93:12)
    at Sensor.<anonymous> (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/index.js:81:21)
    at Sensor.emit (node:events:527:28)
    at Sensor.emit (/usr/lib/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/Delegate.js:174:13)
    at Gateway.analyseFullState (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:880:34)
    at Gateway.poll (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:733:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Gateway.heartbeat (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:276:9)
[8/8/2022, 9:51:56 AM] [deCONZ] FoH Ian: error: TypeError: Cannot read properties of undefined (reading 'lastUpdated')
    at Switch.updateState (/usr/lib/node_modules/homebridge-deconz/lib/DeconzService/Switch.js:62:24)
    at Switch.update (/usr/lib/node_modules/homebridge-deconz/lib/DeconzService/index.js:93:12)
    at Sensor.<anonymous> (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/index.js:81:21)
    at Sensor.emit (node:events:527:28)
    at Sensor.emit (/usr/lib/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/Delegate.js:174:13)
    at Gateway.analyseFullState (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:880:34)
    at Gateway.poll (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:733:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Gateway.heartbeat (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:276:9)
[8/8/2022, 9:51:56 AM] [deCONZ] FoH Eli and Ki: error: TypeError: Cannot read properties of undefined (reading 'lastUpdated')
    at Switch.updateState (/usr/lib/node_modules/homebridge-deconz/lib/DeconzService/Switch.js:62:24)
    at Switch.update (/usr/lib/node_modules/homebridge-deconz/lib/DeconzService/index.js:93:12)
    at Sensor.<anonymous> (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/index.js:81:21)
    at Sensor.emit (node:events:527:28)
    at Sensor.emit (/usr/lib/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/Delegate.js:174:13)
    at Gateway.analyseFullState (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:880:34)
    at Gateway.poll (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:733:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Gateway.heartbeat (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:276:9)
`

I rolled back to 0.0.17 and those errors went away. I don't know any more than that, but I can try to give you any other info you need. Thanks for all of your work on this.

**Comment by ebaauw** [comment]
v0.0.19.

**Comment by ctj99git** [comment]
> v0.0.19.

Confirmed goodness. Thanks!
