### ISSUE TITLE
Intermittent TypeError on enabling adaptive lighting on some devices at Homebridge startup.

### ISSUE THREAD

**Issue by Monofin** [ebaauw/homebridge-deconz#78]
Deconz v2.19.1
homebridge-deconz v0.0.23

Am picking up this chain of errors on Homebridge startup, once every few restarts:

[26/10/2022, 15:25:25] [deCONZ] Snug Standard Lamp: adaptive lighting: enabled
[26/10/2022, 15:25:25] [deCONZ] Snug Standard Lamp: error: TypeError: Cannot read properties of undefined (reading 'generateControl')
    at CharacteristicDelegate.getter [as _getter] (/usr/lib/node_modules/homebridge-deconz/lib/DeconzService/Light.js:210:40)
    at CharacteristicDelegate._onGet (/usr/lib/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/CharacteristicDelegate.js:354:26)
    at CharacteristicValueTransitionControl.emit (node:events:513:28)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1592:14
    at new Promise (<anonymous>)
    at CharacteristicValueTransitionControl.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1590:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)

It doesn't seem to affect functionality much if at all, but makes for a nice set of logs :-)

**Comment by ebaauw** [comment]
I hope it's fixed in v0.0.24, but it's hard to test for intermittent errors.
