### ISSUE TITLE
TRÅDFRI on/off switch: error: TypeError, since v0.1.0 update

### ISSUE THREAD

**Issue by Monofin** [ebaauw/homebridge-deconz#94]
Hi there: 

Since the update to homebridge-deconz v0.1.0 (which is otherwise really good, thank you for all the work!), my Tradfri switches have ceased functioning, giving the following error at the homebridge logs when they are pressed:

[22/01/2023, 22:29:26] [deCONZ] TRÅDFRI on/off switch: error: TypeError: Cannot read properties of undefined (reading 'values')
    at Switch.updateState (/usr/lib/node_modules/homebridge-deconz/lib/DeconzService/Switch.js:81:52)
    at Switch.update (/usr/lib/node_modules/homebridge-deconz/lib/DeconzService/index.js:104:12)
    at Sensor.<anonymous> (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/index.js:88:19)
    at Sensor.emit (node:events:513:28)
    at Sensor.emit (/usr/lib/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/Delegate.js:172:13)
    at WsClient.<anonymous> (/usr/lib/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:448:23)
    at WsClient.emit (node:events:513:28)
    at WebSocket.<anonymous> (/usr/lib/node_modules/homebridge-deconz/lib/Deconz/WsClient.js:116:26)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/usr/lib/node_modules/homebridge-deconz/node_modules/ws/lib/websocket.js:1180:20)

System: deCONZ v.2.20.01 (beta, debian/ubuntu packages, aarch64, not Pi!)

(I will take a look myself in the morning, UK time as well, but recording the issue for a fix)

**Comment by ebaauw** [comment]
Also reported in Discord.  Should be fixed in v0.1.1.

**Comment by Monofin** [comment]
Confirmed fixed in v0.1.1, closing.
